version: '2'
services:
  web:
    build: .
    command: 'crystal run src/app.cr'
    working_dir: /app/user
    environment:
      DATABASE_URL: 'postgres://postgres:password@pg:5432/postgres'
    ports:
      - '80:3000'
    depends_on:
      - pg
  spec:
    build: .
    command: 'crystal spec'
    working_dir: /app/user
    volumes:
      - '.:/app/user'
  pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'password'
    volumes_from:
      - data
  data: 
    image: heroku/cedar
    volumes:
      - '/var/lib/postgres/data'
