version: '2'
services:
  web:
    build: .
    image: blog-kemalyst
    command: 'crystal run src/app.cr'
    working_dir: /app/user
    environment:
      DATABASE_URL: 'postgres://postgres:password@pg:5432/postgres'
    ports:
      - '80:3000'
    volumes:
      - '.:/app/user'
    depends_on:
      - pg

  spec:
    build: .
    command: 'crystal spec'
    working_dir: /app/user
    volumes_from:
      - web
  
  migrate:
    image: blog-kemalyst
    command: 'crystal run db/migrate.cr'
    working_dir: /app/user
    environment:
      DATABASE_URL: 'postgres://postgres:password@pg:5432/postgres'
    volumes_from:
      - web
    depends_on:
      - pg

  pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'password'
    volumes_from:
      - data
  
  data: 
    image: drujensen/crystal
    volumes:
      - '/var/lib/postgres/data'
